# Generated by Django 4.2.2 on 2023-07-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProCategory',
        ),
    ]
