# Generated by Django 4.2.2 on 2023-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_category_procategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='procategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
