# Generated by Django 4.2.2 on 2023-07-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_procategory_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProCategory',
            new_name='Category',
        ),
    ]
