# Generated by Django 4.2.2 on 2023-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_procategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='brand_images')),
            ],
        ),
    ]
