# Generated by Django 4.2.2 on 2023-07-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_color_gendertype_product_productvariant_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='displayimage',
        ),
    ]
