# Generated by Django 4.2.2 on 2023-07-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofileapp', '0003_useraddress_is_delivery_address_and_more'),
        ('Cartapp', '0003_alter_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Userprofileapp.useraddress'),
        ),
    ]
