# Generated by Django 4.2.2 on 2023-07-16 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofileapp', '0002_rename_user_address_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_delivery_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit number without leading zeros.', regex='^[1-9]\\d{9}$')]),
        ),
    ]
