# Generated by Django 4.2.2 on 2023-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofileapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
