# Generated by Django 4.2.2 on 2023-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
