from django.urls import path
from . import views
urlpatterns = [
    # path('admin-login/',views.admin_login,name='admin-login'),
    path('admin-logout/',views.admin_logout,name='admin-logout'),
    path('admin-home/',views.admin_home,name='admin-home'),
    path('user-list/',views.user_list,name='user-list'),
    path('block-user/<int:id>/',views.block_user,name='block-user'),
    path('unblock-user/<int:id>/',views.unblock_user,name='unblock-user'),
    path('category-list/',views.category_list,name='category-list'),
    path('category-disable/<int:id>/',views.disable_category,name='category-disable'),
    path('category-enable/<int:id>/', views.enable_category, name='category-enable'),
    path('category/<int:id>/edit/', views.edit_category, name='edit-category'),
    path('category-add', views.add_category, name='add-category'),
    path('product-list', views.product_list, name='product-list'),
    path('products/disable/<int:product_id>/', views.disable_product, name='disable-product'),
    path('products/enable/<int:product_id>/', views.enable_product, name='enable-product'),
    path('product-view/<int:product_id>/',views.product_view,name='product-view'),
    path('product-view/<int:product_id>/disable-variant/<int:variant_id>/', views.disable_variant, name='disable-variant'),
    path('product-view/<int:product_id>/enable-variant/<int:variant_id>/', views.enable_variant, name='enable-variant'),
    path('product-view/<int:product_id>/add-variant/', views.add_variant, name='add-variant'),
    path('product/<int:product_id>/variant/<int:variant_id>/edit/', views.edit_variant, name='edit-variant'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit-product'),
    path('product-add/', views.add_product, name='add-product'),
    path('order/', views.admin_orders, name='admin_orders'),
    path('order/<int:order_id>/', views.admin_order_view, name='admin_order_view'),
    path('order/<int:order_id>/shipped/', views.order_shipped, name='order_shipped'),
    path('order/<int:order_id>/delivered/', views.order_delivered, name='order_delivered'),
    path('order/<int:order_id>/cancel/', views.admin_order_cancel, name='admin_order_cancel'),
]